apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: gitops-fromsecret
spec:
  object-templates:
  - objectDefinition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: acm-gitops-repo
        namespace: openshift-gitops
        labels:
          argocd.argoproj.io/secret-type: repository
      stringData:
        url: '{{hub (fromSecret "openshift-gitops" "acm-gitops-repo" "url") hub}}'
        username: '{{hub (fromSecret "openshift-gitops" "acm-gitops-repo" "username") hub}}'
        password: '{{hub (fromSecret "openshift-gitops" "acm-gitops-repo" "password") hub}}'
      type: Opaque

